function reconnectedfile=elongatetrack(file,handles)
% function reconnectedfile=elongatetrack(file,handles)
% Takes .trc files generated by initial tracking
% calls reconnect.m to reconnects trajectories 
% for gaussiantrack.m
%
% MR mar 06 - v1.0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

warning off MATLAB:MKDIR:DirectoryExists
path=cd;
control=1;
[namefile,rem]=strtok(file,'.');
maxblink=str2num(handles.blink);
distmax=str2num(handles.distmax);
mintrace=str2num(handles.mintrace);

%reconnection
disp('  ');
disp('Reconnecting trajectories...');
waitbarhandle=waitbar( 0,'Please wait...','Name',['Reconnecting trajectories in ',file]);
[reconnectedfile,newind]=reconnect(path,file,maxblink,distmax,mintrace,handles,waitbarhandle);
close(waitbarhandle);

%save everything
save(['trc',filesep,namefile,'.con.trc'],'reconnectedfile','-ascii','-tabs');
filetxt=['trc',filesep,namefile,'.con.trc'];
fi = fopen(filetxt,'w');
if fi<3
   error('File not found or readerror.');
else
   fprintf(fi,'%6.2f\t %6.2f\t %6.8f\t %6.8f\t %6.8f\r',reconnectedfile');
end
% close
fclose(fi);

%sauve les trc individuelles
if (length(reconnectedfile)>0) 
  if isdir(['trc',filesep,'molecules']);else;mkdir(['trc',filesep,'molecules']);end;
  MaxPart = max(reconnectedfile(:,1));
  iTrc=[];
  for Ipart=1:MaxPart
	iTrc = reconnectedfile(find(reconnectedfile(:,1)==Ipart),2:4);
    save(['trc',filesep,'molecules',filesep,namefile,'.con.molecule.',num2str(Ipart),'.trc.dat'],'iTrc','-ascii');
  end
  % index
  save(['ind',filesep,namefile,'.con.ind'],'newind','-ascii'); 
else
  disp('Empty .con.trc file');
  %report
  text=['No trajectories to reconnect...'];
  updatereport(handles,text,1)
end

%end of file


