function reconnectedfile=elongatetrackMIA(file,trcfile,handles)
% function reconnectedfile=elongatetrackMIA(file,handles)
% Takes .MIA.trc files generated by MIA tracking
% calls blinking.m to reconnects trajectories 
% for MIAtrack.m
%
% MR mar 06 - v1.0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

warning off MATLAB:MKDIR:DirectoryExists
path=cd;
control=1;
[namefile,rem]=strtok(file,'.');
maxblink=str2num(handles.blink);
distmax=str2num(handles.distmax);
mintrace=str2num(handles.mintrace);

%reconnection
disp('  ');
disp('Reconnecting trajectories...');
waitbarhandle=waitbar( 0,'Please wait...','Name',['Reconnecting trajectories in ',file]);
% initialTRCfile=fullfile(namefile,'.MIA',filesep,'tracking',filesep,namefile,'_MIA.trc']; %trajectoria dada por MIA
% initialTRCfile=trcfile;
% % by CMT 19/10/2007
tic
% %
reconnectedfile=blinking(trcfile,maxblink,distmax,mintrace,handles,waitbarhandle);
% reconnectedfile=blinkingLC(trcfile,maxblink,distmax,mintrace,handles,waitbarhandle);
% % by CMT 19/10/2007
toc
close(waitbarhandle);
if(isempty(reconnectedfile))
  return
end;
Ntracefin=max(reconnectedfile(:,1));
if Ntracefin>0
    
% save everything
if isdir(['trc',filesep]);else;mkdir(['trc',filesep]);end;
save(['trc',filesep,namefile,'.MIA.con.trc'],'reconnectedfile','-ascii','-tabs');
filetxt=['trc',filesep,namefile,'.MIA.con.trc'];
fi = fopen(filetxt,'w');
if fi<3
   error('File not found or readerror.');
else
   fprintf(fi,'%6.2f\t %6.2f\t %6.8f\t %6.8f\t %6.8f %6.8f\r',reconnectedfile');
end
fclose(fi);

if isdir(['trc',filesep,'molecules']);else;mkdir(['trc',filesep,'molecules']);end;
MaxPart = max(reconnectedfile(:,1));
iTrc=[];
for Ipart=1:MaxPart
	iTrc = reconnectedfile(find(reconnectedfile(:,1)==Ipart),2:4);
    save(['trc',filesep,'molecules',filesep,namefile,'.MIA.con.molecule.',num2str(Ipart),'.trc.dat'],'iTrc','-ascii'); % individual trajectories
end

end

%end of file


