function reconnecttrack(file,handles)
% function reconnectMIA
% Takes .trc files generated by MIA tracking
% reconnects trajectories using 
%       maxblink: maximum amount of frames for a blinking event
%       distmax: maximum distance allowed to move during a blinking event


warning off MATLAB:MKDIR:DirectoryExists
path=cd;
control=1;

  
maxblink=str2num(handles.blink);
distmax=str2num(handles.distmax);
mintrace=str2num(handles.mintrace);


% trc file
[namefile,rem]=strtok(file,'.');  % sin extension
initialTRCfile=[path,filesep,'trc',filesep,namefile,'.trc']

%reconnection
disp('  ');
disp('Reconnecting trajectories...');
reconnectedfile=blinking(initialTRCfile,maxblink,distmax,mintrace);

Ntracefin=max(reconnectedfile(:,1));

if Ntracefin>0
    % guarda trajectorias reconectadas con formato compatible para msdturbo
    %[savefile,rem]=strtok(file,'_');  %'sin _MIA.trc'
    save(['trc',filesep,namefile,'.MIA.con.trc'],'reconnectedfile','-ascii','-tabs'); 
    %%%%converti pour msd turbo
           % filetxt=['trc\',namefile,'.MIA.con.trc'];
            %fi = fopen(filetxt,'w');
        %    if fi<3
         %     error('File not found or readerror.');
         %  else
         %     fprintf(fi,'%6.2f\t %6.2f\t %6.8f\t %6.8f\t %6.2f\t %6.2f\t %6.8f\r',reconnectedfile');
         %  end
            % close
         %   fclose(fi);
    %%%%%%%%%%fin conversion
end

